apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: hello-world
    env: dev
  name: hello-world
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world
      env: dev
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hello-world
        env: dev
    spec:
      containers:
      - image: sltet/hello-world:v1
        imagePullPolicy: Always
        name: hello-world
        ports:
        - containerPort: 8080
        resources: {}
status: {}
