apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: hello-world
    env: dev
  name: hello-world
  namespace: dev
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: hello-world
    env: dev
  type: NodePort
status:
  loadBalancer: {}
